services:
  rust_axum_postgres:
    image: postgres:16-alpine
    container_name: rust_axum_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: axum_rest_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rust_axum_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rust_axum_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

volumes:
  postgres_data:
